# Generated by Django 2.0.5 on 2018-07-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0002_customerservice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
