# Generated by Django 2.0.5 on 2018-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0003_auto_20180725_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='description',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
