# Generated by Django 2.0.5 on 2018-07-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0004_auto_20180725_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerservice',
            name='description',
        ),
    ]
