# Generated by Django 2.0.5 on 2018-07-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0005_remove_customerservice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='description',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
