# Generated by Django 2.0.5 on 2018-07-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0006_customerservice_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerservice',
            old_name='u_name',
            new_name='name',
        ),
    ]
